# Project meta-data
[project]
name = "project-name"
version = "0.1.0"
description = "Short project description"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
app = "project_name.main:main"

# Dependencies for development
[dependency-groups]
dev = [
  "mypy",
  "pre-commit",
  "pytest",
  "pytest-asyncio",
  "ruff",
]

# System and module used for building
[build-system]
requires = ["uv_build>=0.12.13,<0.13"]
build-backend = "uv_build"

# Mypy
[tool.mypy]
python_version = "3.14"
strict = true
warn_unreachable = true
pretty = true
files = ["src", "tests"]

# Ruff used for linting and formatting
[tool.ruff]
target-version = "py314"
line-length = 88

[tool.ruff.lint]
extend-select = [
  "B",  # flake8-bugbear,
  "I"  # Isort
]
ignore = ["E501"]  # Don't enforce line-length violations

unfixable = ["B"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
